name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: GaryMK/WakaTime@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 07d4b108e1020b8da989efb299ab0105
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
